print("Hyderabad")
print("Banglore")
print("Indore")
print("Vizag")
print("tirupathi")
print("Budval")
print("RJY")
print("Guntur")
print("Kurnool")
print("Hitech City")
print("Chennai")
print("Mumbai")
print("Delhi")
print("Kochi")
print("Kolkata")
print("Imphal")
print("Luknow")
print("Jaiput")
